<?php

########################################################################
# Extension Manager/Repository config file for ext: "ws_map"
#
# Auto generated by Extbase Kickstarter 2011-03-01
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Graphical map of offices',
	'description' => 'You can use this map as map for branches or another objects. All objects are configured from BE',
	'category' => 'plugin',
	'author' => 'Nikolay Orlenko',
	'author_email' => 'info@web-spectr.com',
	'author_company' => 'Web.Spectr: http://web-spectr.com',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>